
# MIDI MAP CC on CHANNEL 1
[midi_map.cc.1]
# midi cc 1 on channel 1 is assigned to a TrackSampleSelect control, for track 0
1 = { TrackSampleSelect = { tcode = 0, val = 0.0, track_num = 0 } }
# midi cc 7 on channel 1 is assigned to a TrackVolume control, for track 0
7 = { TrackVolume = { tcode = 0, val = 0.0, track_num = 0 } }
# midi cc 10 on channel 1 is assigned to a TrackPan control, for track 0
10 = { TrackPan = { tcode = 0, val = 0.5, track_num = 0 } }
# MIDI MAP CC on CHANNEL 2
[midi_map.cc.2]
# midi cc 1 on channel 1 is assigned to a TrackSampleSelect control, for track 0
1 = { TrackSampleSelect = { tcode = 0, val = 0.0, track_num = 1 } }
# midi cc 7 on channel 2 is assigned to a TrackVolume control, for track 1
7 = { TrackVolume = { tcode = 0, val = 0.0, track_num = 1 } }
# midi cc 10 on channel 2 is assigned to a TrackPan control, for track 1
10 = { TrackPan = { tcode = 0, val = 0.5, track_num = 1 } }


